version: "3.9"

services:
  db:
    container_name: mylp
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}"]
      interval: 7s
      timeout: 4s
      retries: 5
#     volumes:
#       - ./build.sql:/docker-entrypoint-initdb.d/build.sql
#       - db-viva:/var/lib/postgresql/data

# volumes:
#   db-viva:
#     driver: local
